# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20180123_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='iew',
            new_name='views',
        ),
    ]
